"""Initial migration

Revision ID: ca0193bf4001
Revises: 
Create Date: 2025-10-20 04:28:03.078151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0193bf4001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dns_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('record_type', sa.String(length=10), nullable=False),
    sa.Column('record_name', sa.String(length=255), nullable=True),
    sa.Column('record_value', sa.Text(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dns_records_domain'), ['domain'], unique=False)

    op.create_table('emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('sender', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('domain', sa.String(length=255), nullable=True),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('clicked', sa.Boolean(), nullable=True),
    sa.Column('bounced', sa.Boolean(), nullable=True),
    sa.Column('bounce_type', sa.String(length=20), nullable=True),
    sa.Column('complaint', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('clicked_at', sa.DateTime(), nullable=True),
    sa.Column('bounced_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emails_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_recipient'), ['recipient'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_sent_at'), ['sent_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emails_status'), ['status'], unique=False)

    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('warmup_stage', sa.Integer(), nullable=True),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_bounced', sa.Integer(), nullable=True),
    sa.Column('total_complaints', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_addresses')
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emails_status'))
        batch_op.drop_index(batch_op.f('ix_emails_sent_at'))
        batch_op.drop_index(batch_op.f('ix_emails_recipient'))
        batch_op.drop_index(batch_op.f('ix_emails_priority'))
        batch_op.drop_index(batch_op.f('ix_emails_domain'))
        batch_op.drop_index(batch_op.f('ix_emails_created_at'))
        batch_op.drop_index(batch_op.f('ix_emails_batch_id'))

    op.drop_table('emails')
    with op.batch_alter_table('dns_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dns_records_domain'))

    op.drop_table('dns_records')
    # ### end Alembic commands ###
