version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: smtp_enterprise
      POSTGRES_USER: smtp_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U smtp_admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 4gb
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: smtp_queue
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  smtp-api:
    image: enterprise-smtp-server:latest
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    ports:
      - "5000:5000"
    volumes:
      - ./logs:/app/logs
      - ./keys:/app/keys
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '2'
          memory: 2G

  smtp-worker:
    image: enterprise-smtp-server:latest
    command: python app/workers/email_worker.py
    depends_on:
      - postgres
      - redis
      - rabbitmq
    environment:
      DB_HOST: postgres
      REDIS_HOST: redis
      RABBITMQ_HOST: rabbitmq
    deploy:
      replicas: 20
      resources:
        limits:
          cpus: '1'
          memory: 1G

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
